name: zentheme
description: Deploy a zensical website with BrokenSource commons

runs:
  using: composite
  steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v8.2.0
    - run: uvx --from git+https://github.com/BrokenSource/Pages/ pages-make
      shell: bash
